[bastion]
bastion ansible_host=192.168.55.30 ansible_user=ubuntu

[kube_control_plane]
cp-01 ansible_host=192.168.55.10 ansible_user=ubuntu

[kube_node]
worker-01 ansible_host=192.168.55.11 ansible_user=ubuntu
worker-02 ansible_host=192.168.55.12 ansible_user=ubuntu

[db]
db-server ansible_host=192.168.55.20 ansible_user=ubuntu

[k8s_cluster:children]
kube_control_plane
kube_node
